# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02461e4466fc187b65939dbd8a843b861924556806c58a6ec0ff815cca071d6b3617de0e64c8afa70d813c216c37a5fae782b82ed5720da9e32eebe934245724

test:
  secret_key_base: 4b26b94c2a3b2419c7e8d02bb1592e19a037998be54847a03f5137c60b6fcee4216419ea317bf1233a798f12842e1593d7b8eb3b07fe30c35c244ead5c7b3341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
